# Generated by Django 5.0.1 on 2024-01-08 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('category_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('actual_price', models.IntegerField(blank=True)),
                ('our_price', models.IntegerField(blank=True)),
                ('rating_count', models.IntegerField(blank=True)),
                ('review_count', models.IntegerField(blank=True)),
                ('packge_fee', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('delivery', models.IntegerField(blank=True)),
                ('rating', models.FloatField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('size', models.CharField(blank=True, max_length=200)),
                ('warranty', models.IntegerField(blank=True)),
                ('offer', models.IntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.categorymodel')),
            ],
        ),
    ]
