# Generated by Django 5.0.1 on 2024-01-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_gendermodel_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.gendermodel'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='mob',
            field=models.BigIntegerField(null=True),
        ),
    ]
