# Generated by Django 5.0.1 on 2024-01-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='offer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
