# Generated by Django 5.0.1 on 2024-01-31 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_cartitem_offer_cartitem_price_cartitem_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.productmodel'),
        ),
    ]
