# Generated by Django 5.0.1 on 2024-02-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_productmodel_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='stock',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
